---
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: cluster-console-notification
spec:
  backgroundColor: "{{ .Values.backgroundColor }}"
  color: "{{ .Values.color }}"
  location: BannerBottom
  text: "{{ .Values.text }}"
